
# To set up markers and extract data

1. insert usb
2. open data viewer
3. import participant data files
	- file > import data > multiple eyelink data files
4. preferences > cyclopean mode (checked) this creates a variable that is the average between left and right eyes (to make sure we have the eye tracked)
5. remove data before audio onset. clic on Full Trial Period > edit > blank page icon > 
  - name the interest period: audio_onset_end_sentend
  - Interest period start event "Message Text": SENTENCE_ONSET
  - Interest period end event "Message Text": end_sentence
  - "OK"
  - "OK" again to select that time period
6. Regroup to remove practice trials
	- right click main folder, select 'trial regrouping'
	- select 'exp', regroup
	- delete 'ps', 'pl', 'pd'
	- RUN EVERYTHING FOR EACH EXPERIMENT
		- duration (get sample report with specific interest periods)
7. To extract one report per experiment:
  - highlight that experiment after regrouping (e.g. stress)
  - on bottom left menu, check: "Exclude from Reports"
  - repeat with the rest of experiments you want to exclude from that report

Alternative for selecting a time-period:		
8. make marker/time period (to limit output)
	- sliding menu thing, click 'edit'
	- click new interest period icon
	- make a message event, then click 'details'
	- Duration
		- Start Time Message text = 'word4_C1V1'
		- Start time offset = 0
		- End time message text = 'end_sentence'
		- end time offset = 200
	- Lexical
		- Start Time Message text = 'word2_C1V1'
		- Start time offset = 0
		- End time message text = 'end_sentence'
		- end time offset = 200
	- Stress
		- Start Time Message text = 'word2_c1v1' (changed to 1st lm before target word)
		- Start time offset = 0
		- End time message text = 'word5'
		- end time offset = 200
9. make report
	- analysis > reports > Time Course Binning Analysis 
	- select all variables 
	- Bin Interval in ms: 10ms/50ms... 
	- this will make 'file.txt'
*10. run python script (VisualWorld.py)
	- open terminal
	- cd to location of 'VisualWorld.py' and 'file.txt'
	- run: 'python VisualWorld.py'
	- select file: 'file.txt'
	(we don't need this step anymore)
	
7. DF
	- RIGHT_0_P = elsewhere
	- RIGHT_1_C = target
	- RIGHT_2_C = distractor








# Changing interest areas

- change grouping from grp to trialside (edit > trial grouping)
- select 'left'
- create new area (delete old ones)
- set ID as 1 for target, 2 for distractor (save as target on left, distractor on right)
- Set IA: 
	- rt side: 0, 0, 960, 1080
	- lt side: 960 0 1920 1080
- save entire new IA (save to disk > targetLeft)
- do the same for right side
- repeat for every experiment


# Create binned output

- Open data w/ dataviewer .6 or higher
- Select "Time Course (binned) Analysis report"
- We are using 10, 20 and 50ms bins
- Select OPT1 = , use fixation and saccades


# colNames

RECORDING_SESSION_LABEL
TRIAL_LABEL
TRIAL_INDEX
BIN_INDEX
exp
id
identifier
sentence
verb
sentencewav
startsentence
word1
word2_c1v1
word2_20msafterv1
word2_c2
word2_c3
word2_v2
word3_20msafterv1
word3_c1v1
word3_c2
word3_c3
word3_suffix
word4_c1v1
word4_20msafterv1
word4_c1
word4_suffix
word5
word6
word7
end_sentence
target
targetside
BIN_DURATION
BIN_END_TIME
BIN_SAMPLE_COUNT
BIN_START_TIME
EYE_TRACKED
IA_1_ID
IA_2_ID
IA_0_ID
RIGHT_IA_1_SAMPLE_COUNT
RIGHT_IA_2_SAMPLE_COUNT
RIGHT_IA_0_SAMPLE_COUNT
RIGHT_IA_1_SAMPLE_COUNT_%
RIGHT_IA_2_SAMPLE_COUNT_%
RIGHT_IA_0_SAMPLE_COUNT_%
correctresponse
KEY_PRESSED















